const CONFIG={SPREADSHEET_ID:'PASTE_GOOGLE_SHEET_ID_HERE',COORDINATOR_KEY:'CHANGE_THIS_COORDINATOR_KEY'};
const CASES=[
{id:'CASE-01',condition:'clear',title:'Checkout latency and CPU saturation',incident:'Checkout requests are failing or becoming slow during the incident window.',evidence:['checkoutservice CPU rises sharply after the injection.','checkoutservice latency-90 also increases.','The strongest abnormality is localized to checkoutservice CPU.'],options:['Checkoutservice CPU/resource saturation','Emailservice latency issue']},
{id:'CASE-02',condition:'ambiguous',title:'Checkout memory pressure with error-like logs',incident:'Checkout performance degrades, but the evidence does not cleanly isolate one explanation.',evidence:['checkoutservice memory changes after injection.','Error-like log activity is also present.','Both signals are plausible, so further verification is warranted.'],options:['Checkoutservice memory/resource pressure','Frontend error increase']},
{id:'CASE-03',condition:'conflicting',title:'Checkout packet-loss incident',incident:'Checkout latency rises while log-rate evidence points in a competing direction.',evidence:['checkoutservice latency-90 increases after injection.','checkoutservice log-rate evidence changes as well.','The two evidence sources do not independently justify the same conclusion.'],options:['Checkoutservice network packet loss','Emailservice latency issue']},
{id:'CASE-04',condition:'misleading',title:'Distracting emailservice latency',incident:'A visible latency change appears in emailservice, but it is not the injected root cause.',evidence:['emailservice latency-90 changes after injection.','The visible emailservice signal is a distractor.','The actual fault is associated with checkoutservice network loss.'],options:['Emailservice latency is the root cause','Checkoutservice network packet loss']},
{id:'CASE-05',condition:'incomplete',title:'User-service packet loss with missing telemetry',incident:'The user service is affected, but one telemetry source is unavailable.',evidence:['user-service incident evidence indicates network loss.','Metrics and logs are available.','Trace telemetry is unavailable, so the evidence is incomplete.'],options:['User-service network packet loss','User-service memory stress']}];
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return out({ok:true,service:'IncidentIQ Study API'})}
function doPost(e){try{let b=JSON.parse(e.postData.contents||'{}');switch(b.action){case'test':return out(testPayload());case'reserve':return out(reserve());case'resume':return out(resume(b));case'saveTrial':return out(save(b));case'finalize':return out(finalize(b));case'status':return out(status(b.key));case'export':return out(exportZip(b.key,b.participantId||'ALL'));default:return out({ok:false,error:'Unknown action'})}}catch(x){return out({ok:false,error:String(x.message||x)})}}
function ss(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID)}
function sheet(n,h){let s=ss().getSheetByName(n);if(!s)s=ss().insertSheet(n);if(s.getLastRow()===0)s.appendRow(h);return s}
function init(){let p=sheet('Participants',['participantId','arm','status','token','reservedAt','completedAt','caseOrder']);if(p.getLastRow()<=1){let a=[];const orders=[[0,1,2,3,4],[0,1,2,4,3],[0,1,3,2,4],[0,1,3,4,2],[0,1,4,2,3],[0,1,4,3,2],[0,2,1,3,4],[0,2,1,4,3],[0,2,3,1,4],[0,2,3,4,1],[0,2,4,1,3],[0,2,4,3,1],[0,3,1,2,4],[0,3,1,4,2],[0,3,2,1,4],[0,3,2,4,1],[0,3,4,1,2],[0,3,4,2,1],[0,4,1,2,3],[0,4,1,3,2],[0,4,2,1,3],[0,4,2,3,1],[0,4,3,1,2],[0,4,3,2,1],[1,0,2,3,4],[1,0,2,4,3],[1,0,3,2,4],[1,0,3,4,2],[1,0,4,2,3],[1,0,4,3,2]];for(let i=1;i<=30;i++){let id='P'+('0'+i).slice(-2),arm=i<=10?'human_only':i<=20?'generic_ai':'incidentiq',o=orders[i-1];a.push([id,arm,'available','','','',''+o.join(',')])}p.getRange(2,1,a.length,7).setValues(a)}sheet('Results',['recordId','participantId','trialIndex','caseId','condition','diagnosis','confidence','workload','aiFollowed','aiOverridden','elapsedSeconds','savedAt'])}
function testPayload(){return{ok:true,test:true,participantId:'TEST',token:'TEST-ONLY',completedTrials:[],trials:CASES.map((c,i)=>trial(c,i,'incidentiq'))}}function reserve(){init();let lock=LockService.getScriptLock();lock.waitLock(10000);try{let s=ss().getSheetByName('Participants'),v=s.getDataRange().getValues();for(let r=1;r<v.length;r++)if(v[r][2]==='available'){let id=v[r][0],token=Utilities.getUuid();s.getRange(r+1,3,1,3).setValues([['reserved',token,new Date()]]);return payload(id,v[r][1],token,v[r][6])}return{ok:false,full:true,error:'Study Full'}}finally{lock.releaseLock()}}
function resume(b){init();let s=ss().getSheetByName('Participants'),v=s.getDataRange().getValues();for(let r=1;r<v.length;r++)if(v[r][0]===b.participantId&&v[r][3]===b.token&&v[r][2]!=='completed')return payload(v[r][0],v[r][1],b.token,v[r][6]);throw Error('Resume token invalid')}
function payload(id,arm,token,order){let done=results(id).map(x=>x.trialIndex),used={};done.forEach(x=>used[x]=1);let arr=String(order).split(',').map(Number);return{ok:true,participantId:id,token,completedTrials:done,trials:arr.map((n,i)=>trial(CASES[n],i,arm))}}
function trial(c,i,arm){let x={trialIndex:i+1,caseId:c.id,condition:c.condition,title:c.title,incident:c.incident,evidence:c.evidence,options:c.options};if(arm==='generic_ai')x.assistance={text:'The strongest salient observation is highlighted. Treat it as one input, not guaranteed truth.',highlight:c.evidence[0]};if(arm==='incidentiq')x.assistance={text:'Evidence-grounded assistance: compare supporting and contradictory evidence before deciding.',supporting:c.evidence.slice(0,2),uncertainty:c.condition==='clear'?'low':'elevated'};return x}
function results(id){let s=sheet('Results',['recordId','participantId','trialIndex','caseId','condition','diagnosis','confidence','workload','aiFollowed','aiOverridden','elapsedSeconds','savedAt']),v=s.getDataRange().getValues(),a=[];for(let r=1;r<v.length;r++)if(v[r][1]===id)a.push({trialIndex:Number(v[r][2]),row:r+1});return a}
function auth(id,t){let s=ss().getSheetByName('Participants'),v=s.getDataRange().getValues();for(let r=1;r<v.length;r++)if(v[r][0]===id&&v[r][3]===t&&v[r][2]!=='completed')return true;throw Error('Participant authentication failed')}
function save(b){init();auth(b.participantId,b.token);if(!Number.isInteger(b.trialIndex)||b.trialIndex<1||b.trialIndex>5)throw Error('Invalid trial');if(!CASES.some(c=>c.id===b.caseId))throw Error('Invalid case');if(!b.diagnosis)throw Error('Diagnosis required');if(![1,2,3,4,5].includes(Number(b.confidence)))throw Error('Confidence must be 1-5');if(![1,2,3,4,5].includes(Number(b.workload)))throw Error('Workload must be 1-5');let s=ss().getSheetByName('Results'),v=s.getDataRange().getValues(),c=CASES.find(x=>x.id===b.caseId);for(let r=1;r<v.length;r++)if(v[r][1]===b.participantId&&Number(v[r][2])===b.trialIndex){s.getRange(r+1,1,1,12).setValues([[v[r][0],b.participantId,b.trialIndex,b.caseId,c.condition,b.diagnosis,Number(b.confidence),Number(b.workload),b.aiFollowed===true,b.aiOverridden===true,Number(b.elapsedSeconds||0),new Date()]]);return{ok:true,updated:true}}s.appendRow([Utilities.getUuid(),b.participantId,b.trialIndex,b.caseId,c.condition,b.diagnosis,Number(b.confidence),Number(b.workload),b.aiFollowed===true,b.aiOverridden===true,Number(b.elapsedSeconds||0),new Date()]);return{ok:true,saved:true}}
function finalize(b){init();auth(b.participantId,b.token);if(results(b.participantId).length<5)throw Error('Complete all 5 trials first');let s=ss().getSheetByName('Participants'),v=s.getDataRange().getValues();for(let r=1;r<v.length;r++)if(v[r][0]===b.participantId){s.getRange(r+1,3).setValue('completed');s.getRange(r+1,6).setValue(new Date());break}return{ok:true,completed:true,participantId:b.participantId}}
function status(key){if(key!==CONFIG.COORDINATOR_KEY)throw Error('Coordinator authentication failed');init();let s=ss().getSheetByName('Participants'),v=s.getDataRange().getValues();return{ok:true,participants:v.slice(1).map(r=>({participantId:r[0],arm:r[1],status:r[2],reservedAt:r[4],completedAt:r[5],trialCount:results(r[0]).length}))}}
function exportZip(key,id){if(key!==CONFIG.COORDINATOR_KEY)throw Error('Coordinator authentication failed');init();let s=ss().getSheetByName('Results'),v=s.getDataRange().getValues(),ids=id==='ALL'?Array.from({length:30},(_,i)=>'P'+('0'+(i+1)).slice(-2)):[id],blobs=ids.map(pid=>{let rows=v.slice(1).filter(r=>r[1]===pid).map(r=>({recordId:r[0],participantId:r[1],trialIndex:r[2],caseId:r[3],condition:r[4],diagnosis:r[5],confidence:r[6],workload:r[7],aiFollowed:r[8],aiOverridden:r[9],elapsedSeconds:r[10],savedAt:r[11]}));return Utilities.newBlob(JSON.stringify({participantId:pid,trials:rows},null,2),'application/json',pid+'.json')});let z=Utilities.zip(blobs,id==='ALL'?'IncidentIQ_all_participants.zip':id+'.zip');return{ok:true,fileName:z.getName(),mimeType:z.getContentType(),base64:Utilities.base64Encode(z.getBytes())}}
